APP_NAME = "Fast Backup"
LABEL_CACHE = "label_cache.json"

X_ORIGIN_BUTTON = 200
Y_ORIGIN_BUTTON = 35
X_ORIGIN_LABEL = X_ORIGIN_BUTTON + 200
Y_ORIGIN_LABEL = Y_ORIGIN_BUTTON

X_DESTINATION_BUTTON = X_ORIGIN_BUTTON
Y_DESTINATION_BUTTON = Y_ORIGIN_BUTTON + 40
X_DESTINATION_LABEL = X_DESTINATION_BUTTON + 200
Y_DESTINATION_LABEL = Y_DESTINATION_BUTTON

X_TRIGGER_BUTTON = X_ORIGIN_BUTTON
Y_TRIGGER_BUTTON = Y_DESTINATION_BUTTON + 60


PROGRESSBAR_WIDTH = 150

ROOT_WINDOW_WIDTH = 600
ROOT_WINDOW_HEIGHT = 600

WARNING_WINDOW_WIDTH = 400
WARNING_WINDOW_HEIGHT = 200
